package com.gsroot.bhyx.model;

public class BhUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.uni_id
     *
     * @mbggenerated
     */
    private String uniId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.user_nick
     *
     * @mbggenerated
     */
    private String userNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.pick_vercode
     *
     * @mbggenerated
     */
    private String pickVercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.user_head
     *
     * @mbggenerated
     */
    private String userHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_user_info.leader_user_id
     *
     * @mbggenerated
     */
    private String leaderUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.user_id
     *
     * @return the value of bh_user_info.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.user_id
     *
     * @param userId the value for bh_user_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.uni_id
     *
     * @return the value of bh_user_info.uni_id
     *
     * @mbggenerated
     */
    public String getUniId() {
        return uniId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.uni_id
     *
     * @param uniId the value for bh_user_info.uni_id
     *
     * @mbggenerated
     */
    public void setUniId(String uniId) {
        this.uniId = uniId == null ? null : uniId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.user_nick
     *
     * @return the value of bh_user_info.user_nick
     *
     * @mbggenerated
     */
    public String getUserNick() {
        return userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.user_nick
     *
     * @param userNick the value for bh_user_info.user_nick
     *
     * @mbggenerated
     */
    public void setUserNick(String userNick) {
        this.userNick = userNick == null ? null : userNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.user_mobile
     *
     * @return the value of bh_user_info.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.user_mobile
     *
     * @param userMobile the value for bh_user_info.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.pick_vercode
     *
     * @return the value of bh_user_info.pick_vercode
     *
     * @mbggenerated
     */
    public String getPickVercode() {
        return pickVercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.pick_vercode
     *
     * @param pickVercode the value for bh_user_info.pick_vercode
     *
     * @mbggenerated
     */
    public void setPickVercode(String pickVercode) {
        this.pickVercode = pickVercode == null ? null : pickVercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.create_time
     *
     * @return the value of bh_user_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.create_time
     *
     * @param createTime the value for bh_user_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.user_head
     *
     * @return the value of bh_user_info.user_head
     *
     * @mbggenerated
     */
    public String getUserHead() {
        return userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.user_head
     *
     * @param userHead the value for bh_user_info.user_head
     *
     * @mbggenerated
     */
    public void setUserHead(String userHead) {
        this.userHead = userHead == null ? null : userHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_user_info.leader_user_id
     *
     * @return the value of bh_user_info.leader_user_id
     *
     * @mbggenerated
     */
    public String getLeaderUserId() {
        return leaderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_user_info.leader_user_id
     *
     * @param leaderUserId the value for bh_user_info.leader_user_id
     *
     * @mbggenerated
     */
    public void setLeaderUserId(String leaderUserId) {
        this.leaderUserId = leaderUserId == null ? null : leaderUserId.trim();
    }
}