package com.gsroot.bhyx.model;

public class GoodsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.original_price
     *
     * @mbggenerated
     */
    private Long originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.price
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.cycle
     *
     * @mbggenerated
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.cycle_num
     *
     * @mbggenerated
     */
    private String cycleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.shelves_time
     *
     * @mbggenerated
     */
    private String shelvesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.soldout_time
     *
     * @mbggenerated
     */
    private String soldoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.is_limit
     *
     * @mbggenerated
     */
    private Integer isLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.residue_num
     *
     * @mbggenerated
     */
    private String residueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.is_self
     *
     * @mbggenerated
     */
    private String isSelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.postage
     *
     * @mbggenerated
     */
    private String postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_describe
     *
     * @mbggenerated
     */
    private String goodsDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.leader_commission
     *
     * @mbggenerated
     */
    private Long leaderCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_introduction
     *
     * @mbggenerated
     */
    private String goodsIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_id
     *
     * @return the value of goods_info.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_id
     *
     * @param goodsId the value for goods_info.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_name
     *
     * @return the value of goods_info.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_name
     *
     * @param goodsName the value for goods_info.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.original_price
     *
     * @return the value of goods_info.original_price
     *
     * @mbggenerated
     */
    public Long getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.original_price
     *
     * @param originalPrice the value for goods_info.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Long originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.price
     *
     * @return the value of goods_info.price
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.price
     *
     * @param price the value for goods_info.price
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.cycle
     *
     * @return the value of goods_info.cycle
     *
     * @mbggenerated
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.cycle
     *
     * @param cycle the value for goods_info.cycle
     *
     * @mbggenerated
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.cycle_num
     *
     * @return the value of goods_info.cycle_num
     *
     * @mbggenerated
     */
    public String getCycleNum() {
        return cycleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.cycle_num
     *
     * @param cycleNum the value for goods_info.cycle_num
     *
     * @mbggenerated
     */
    public void setCycleNum(String cycleNum) {
        this.cycleNum = cycleNum == null ? null : cycleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.shelves_time
     *
     * @return the value of goods_info.shelves_time
     *
     * @mbggenerated
     */
    public String getShelvesTime() {
        return shelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.shelves_time
     *
     * @param shelvesTime the value for goods_info.shelves_time
     *
     * @mbggenerated
     */
    public void setShelvesTime(String shelvesTime) {
        this.shelvesTime = shelvesTime == null ? null : shelvesTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.soldout_time
     *
     * @return the value of goods_info.soldout_time
     *
     * @mbggenerated
     */
    public String getSoldoutTime() {
        return soldoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.soldout_time
     *
     * @param soldoutTime the value for goods_info.soldout_time
     *
     * @mbggenerated
     */
    public void setSoldoutTime(String soldoutTime) {
        this.soldoutTime = soldoutTime == null ? null : soldoutTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.is_limit
     *
     * @return the value of goods_info.is_limit
     *
     * @mbggenerated
     */
    public Integer getIsLimit() {
        return isLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.is_limit
     *
     * @param isLimit the value for goods_info.is_limit
     *
     * @mbggenerated
     */
    public void setIsLimit(Integer isLimit) {
        this.isLimit = isLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.order
     *
     * @return the value of goods_info.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.order
     *
     * @param order the value for goods_info.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.residue_num
     *
     * @return the value of goods_info.residue_num
     *
     * @mbggenerated
     */
    public String getResidueNum() {
        return residueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.residue_num
     *
     * @param residueNum the value for goods_info.residue_num
     *
     * @mbggenerated
     */
    public void setResidueNum(String residueNum) {
        this.residueNum = residueNum == null ? null : residueNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.is_self
     *
     * @return the value of goods_info.is_self
     *
     * @mbggenerated
     */
    public String getIsSelf() {
        return isSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.is_self
     *
     * @param isSelf the value for goods_info.is_self
     *
     * @mbggenerated
     */
    public void setIsSelf(String isSelf) {
        this.isSelf = isSelf == null ? null : isSelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.postage
     *
     * @return the value of goods_info.postage
     *
     * @mbggenerated
     */
    public String getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.postage
     *
     * @param postage the value for goods_info.postage
     *
     * @mbggenerated
     */
    public void setPostage(String postage) {
        this.postage = postage == null ? null : postage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_describe
     *
     * @return the value of goods_info.goods_describe
     *
     * @mbggenerated
     */
    public String getGoodsDescribe() {
        return goodsDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_describe
     *
     * @param goodsDescribe the value for goods_info.goods_describe
     *
     * @mbggenerated
     */
    public void setGoodsDescribe(String goodsDescribe) {
        this.goodsDescribe = goodsDescribe == null ? null : goodsDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.create_time
     *
     * @return the value of goods_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.create_time
     *
     * @param createTime the value for goods_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.leader_commission
     *
     * @return the value of goods_info.leader_commission
     *
     * @mbggenerated
     */
    public Long getLeaderCommission() {
        return leaderCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.leader_commission
     *
     * @param leaderCommission the value for goods_info.leader_commission
     *
     * @mbggenerated
     */
    public void setLeaderCommission(Long leaderCommission) {
        this.leaderCommission = leaderCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_introduction
     *
     * @return the value of goods_info.goods_introduction
     *
     * @mbggenerated
     */
    public String getGoodsIntroduction() {
        return goodsIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_introduction
     *
     * @param goodsIntroduction the value for goods_info.goods_introduction
     *
     * @mbggenerated
     */
    public void setGoodsIntroduction(String goodsIntroduction) {
        this.goodsIntroduction = goodsIntroduction == null ? null : goodsIntroduction.trim();
    }
}