package com.gsroot.bhyx.model;

public class GoodsTypeRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_relation.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_relation.goods_type_id
     *
     * @mbggenerated
     */
    private String goodsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_relation.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_relation.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_relation.id
     *
     * @return the value of goods_type_relation.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_relation.id
     *
     * @param id the value for goods_type_relation.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_relation.goods_type_id
     *
     * @return the value of goods_type_relation.goods_type_id
     *
     * @mbggenerated
     */
    public String getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_relation.goods_type_id
     *
     * @param goodsTypeId the value for goods_type_relation.goods_type_id
     *
     * @mbggenerated
     */
    public void setGoodsTypeId(String goodsTypeId) {
        this.goodsTypeId = goodsTypeId == null ? null : goodsTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_relation.goods_id
     *
     * @return the value of goods_type_relation.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_relation.goods_id
     *
     * @param goodsId the value for goods_type_relation.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_relation.order
     *
     * @return the value of goods_type_relation.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_relation.order
     *
     * @param order the value for goods_type_relation.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}