package com.gsroot.bhyx.model;

public class LeaderUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.leader_id
     *
     * @mbggenerated
     */
    private String leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.wx_id
     *
     * @mbggenerated
     */
    private String wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.wx_nick
     *
     * @mbggenerated
     */
    private String wxNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.wx_header
     *
     * @mbggenerated
     */
    private String wxHeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.user_address
     *
     * @mbggenerated
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.team_name
     *
     * @mbggenerated
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.user_wx_account
     *
     * @mbggenerated
     */
    private String userWxAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.account_balance
     *
     * @mbggenerated
     */
    private String accountBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.app_account
     *
     * @mbggenerated
     */
    private String appAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_user_info.app_password
     *
     * @mbggenerated
     */
    private String appPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.leader_id
     *
     * @return the value of leader_user_info.leader_id
     *
     * @mbggenerated
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.leader_id
     *
     * @param leaderId the value for leader_user_info.leader_id
     *
     * @mbggenerated
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId == null ? null : leaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.wx_id
     *
     * @return the value of leader_user_info.wx_id
     *
     * @mbggenerated
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.wx_id
     *
     * @param wxId the value for leader_user_info.wx_id
     *
     * @mbggenerated
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.wx_nick
     *
     * @return the value of leader_user_info.wx_nick
     *
     * @mbggenerated
     */
    public String getWxNick() {
        return wxNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.wx_nick
     *
     * @param wxNick the value for leader_user_info.wx_nick
     *
     * @mbggenerated
     */
    public void setWxNick(String wxNick) {
        this.wxNick = wxNick == null ? null : wxNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.wx_header
     *
     * @return the value of leader_user_info.wx_header
     *
     * @mbggenerated
     */
    public String getWxHeader() {
        return wxHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.wx_header
     *
     * @param wxHeader the value for leader_user_info.wx_header
     *
     * @mbggenerated
     */
    public void setWxHeader(String wxHeader) {
        this.wxHeader = wxHeader == null ? null : wxHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.user_name
     *
     * @return the value of leader_user_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.user_name
     *
     * @param userName the value for leader_user_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.user_address
     *
     * @return the value of leader_user_info.user_address
     *
     * @mbggenerated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.user_address
     *
     * @param userAddress the value for leader_user_info.user_address
     *
     * @mbggenerated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.user_mobile
     *
     * @return the value of leader_user_info.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.user_mobile
     *
     * @param userMobile the value for leader_user_info.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.team_name
     *
     * @return the value of leader_user_info.team_name
     *
     * @mbggenerated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.team_name
     *
     * @param teamName the value for leader_user_info.team_name
     *
     * @mbggenerated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.user_wx_account
     *
     * @return the value of leader_user_info.user_wx_account
     *
     * @mbggenerated
     */
    public String getUserWxAccount() {
        return userWxAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.user_wx_account
     *
     * @param userWxAccount the value for leader_user_info.user_wx_account
     *
     * @mbggenerated
     */
    public void setUserWxAccount(String userWxAccount) {
        this.userWxAccount = userWxAccount == null ? null : userWxAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.lat
     *
     * @return the value of leader_user_info.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.lat
     *
     * @param lat the value for leader_user_info.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.lng
     *
     * @return the value of leader_user_info.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.lng
     *
     * @param lng the value for leader_user_info.lng
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.create_time
     *
     * @return the value of leader_user_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.create_time
     *
     * @param createTime the value for leader_user_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.account_balance
     *
     * @return the value of leader_user_info.account_balance
     *
     * @mbggenerated
     */
    public String getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.account_balance
     *
     * @param accountBalance the value for leader_user_info.account_balance
     *
     * @mbggenerated
     */
    public void setAccountBalance(String accountBalance) {
        this.accountBalance = accountBalance == null ? null : accountBalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.app_account
     *
     * @return the value of leader_user_info.app_account
     *
     * @mbggenerated
     */
    public String getAppAccount() {
        return appAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.app_account
     *
     * @param appAccount the value for leader_user_info.app_account
     *
     * @mbggenerated
     */
    public void setAppAccount(String appAccount) {
        this.appAccount = appAccount == null ? null : appAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_user_info.app_password
     *
     * @return the value of leader_user_info.app_password
     *
     * @mbggenerated
     */
    public String getAppPassword() {
        return appPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_user_info.app_password
     *
     * @param appPassword the value for leader_user_info.app_password
     *
     * @mbggenerated
     */
    public void setAppPassword(String appPassword) {
        this.appPassword = appPassword == null ? null : appPassword.trim();
    }
}