package com.gsroot.bhyx.mapper;

import com.gsroot.bhyx.model.BhUserInfo;

public interface BhUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_user_info
     *
     * @mbggenerated
     */
    int insert(BhUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_user_info
     *
     * @mbggenerated
     */
    int insertSelective(BhUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_user_info
     *
     * @mbggenerated
     */
    BhUserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BhUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BhUserInfo record);
}