package com.gsroot.bhyx.mapper;

import com.gsroot.bhyx.model.OrderGoodsRelation;

public interface OrderGoodsRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_relation
     *
     * @mbggenerated
     */
    int insert(OrderGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_relation
     *
     * @mbggenerated
     */
    int insertSelective(OrderGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_relation
     *
     * @mbggenerated
     */
    OrderGoodsRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderGoodsRelation record);
}