package com.gsroot.bhyx.mapper;

import com.gsroot.bhyx.model.UserLoginInfo;

public interface UserLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ulId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbggenerated
     */
    int insert(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbggenerated
     */
    int insertSelective(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbggenerated
     */
    UserLoginInfo selectByPrimaryKey(String ulId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserLoginInfo record);
}